name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build imagem Docker
      run: docker build -t minha-aplicacao-node .